---
title: "Proyecto Parte 2 Andres Diaz 999013647"
output: html_notebook
---

 


```{r}
#LISTOOO11111
#DOMINIO
#P01I03 ¿Qué edad tenia al irse?	Escala
#P01I05 ¿En qué país se encuentra actualmente?	Nominal


library(rpart)
library(rpart.plot)

migracion <- read.csv('C:/Users/Andres/Desktop/Proyecto parte 2/migracion2.csv', sep = ',')


# Crear el árbol de decisión para la condición
arbol_condicion1 <- rpart(DOMINIO ~
                           
P01I03 +
P01I05,     
                         
                         
                         data = migracion, method = "class")

# Visualizar el árbol de decisión
rpart.plot(arbol_condicion1, type=2, extra=0, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn",
           main = "Predicción del dominio", cex = 1)

```
```{r}
# Caso para predicción 1
migracion_pred <- data.frame(

  P01I05 = c(3001), #¿En qué país se encuentra actualmente?
  P01I03 = c(50) #¿Qué edad tenia al irse?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion1, migracion_pred, type = "class")
result_condicion  # Dominio de Estudio
```

```{r}
# Caso para predicción 2
migracion_pred <- data.frame(

  P01I05 = c(3003), #¿En qué país se encuentra actualmente?
  P01I03 = c(30) #¿Qué edad tenia al irse?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion1, migracion_pred, type = "class")
result_condicion  # Dominio de Estudio
```

```{r}
library(rpart)
library(rpart.plot)

vivienda <- read.csv('C:/Users/Andres/Desktop/Proyecto parte 2/vivienda.csv', sep = ',')


# Crear el árbol de decisión para la condición
arbol_condicion2 <- rpart(DOMINIO ~

P01A02 +
P01A03 +
P01A04 ,
                         
                         data = vivienda, method = "class")

# Visualizar el árbol de decisión
rpart.plot(arbol_condicion2, type=2, extra=0, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn",
           main = "Predicción del dominio", cex = 1)
```
```{r}
# Caso de ejemplo para predicción
vivienda_pred <- data.frame(


P01A04 = c(5), #¿Cuál es el material predominante en el piso?
P01A03 = c(3), #¿Cuál es el material predominante en el techo?
P01A02 = c(5)  #¿Cuál es el material predominante en las paredes exteriores?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion2, vivienda_pred, type = "class")
result_condicion  # Resultado DOMINIO
```
```{r}
# Caso de ejemplo para predicción
vivienda_pred <- data.frame(


P01A04 = c(2), #¿Cuál es el material predominante en el piso?
P01A03 = c(2), #¿Cuál es el material predominante en el techo?
P01A02 = c(3)  #¿Cuál es el material predominante en las paredes exteriores?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion2, vivienda_pred, type = "class")
result_condicion  # Resultado DOMINIO
```





```{r}
library(rpart)
library(rpart.plot)

vivienda2 <- read.csv('C:/Users/Andres/Desktop/Proyecto parte 2/vivienda.csv', sep = ',')


# Crear el árbol de decisión para la condición
arbol_condicion3 <- rpart(DEPTO ~

P01A05A +
P01A05B +
P01A05C 
,
                         
                         data = vivienda2, method = "class")

# Visualizar el árbol de decisión
rpart.plot(arbol_condicion3, type=2, extra=0, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn",
           main = "Predicción del departamento", cex = 1)
```
```{r}
# Caso de ejemplo para predicción
vivienda_pred2 <- data.frame(

P01A05B = c(2), # ¿Esta vivienda esta conectada a una red de drenajes?
P01A05C = c(2), # ¿Esta vivienda esta conectada a una red de distribución de energía eléctrica?
P01A05A = c(2)  # ¿Esta vivienda esta conectada a una red de distribución de agua?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion3, vivienda_pred2, type = "class")
result_condicion  # Mostrar el resultado de la predicción
```
```{r}
# Caso de ejemplo para predicción
vivienda_pred2 <- data.frame(

P01A05B = c(1), # ¿Esta vivienda esta conectada a una red de drenajes?
P01A05C = c(1), # ¿Esta vivienda esta conectada a una red de distribución de energía eléctrica?
P01A05A = c(1)  # ¿Esta vivienda esta conectada a una red de distribución de agua?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion3, vivienda_pred2, type = "class")
result_condicion  # Mostrar el resultado de la predicción
```
```{r}
# Caso de ejemplo para predicción
vivienda_pred2 <- data.frame(

P01A05B = c(2), # ¿Esta vivienda esta conectada a una red de drenajes?
P01A05C = c(1), # ¿Esta vivienda esta conectada a una red de distribución de energía eléctrica?
P01A05A = c(2)  # ¿Esta vivienda esta conectada a una red de distribución de agua?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion3, vivienda_pred2, type = "class")
result_condicion  # Mostrar el resultado de la predicción
```

```{r}
library(rpart)
library(rpart.plot)

vivienda3 <- read.csv('C:/Users/Andres/Desktop/Proyecto parte 2/vivienda.csv', sep = ',')


# Crear el árbol de decisión para la condición 
arbol_condicion4 <- rpart(POBREZA ~

P01D20A +
P01D20D +
P01D20E,
                         
                         data = vivienda3, method = "class")

# Visualizar el árbol de decisión
rpart.plot(arbol_condicion4, type=2, extra=0, under = TRUE, fallen.leaves = TRUE, box.palette = "BuGn",
           main = "Predicción de la pobreza", cex = 1)
```


```{r}
# Caso de ejemplo para predicción
vivienda_pred3 <- data.frame(

P01D20A = c(2), #¿Tiene el hogar servicio de: plan residencial?
P01D20D = c(1), #¿Tiene el hogar servicio de: internet residencial?
P01D20E = c(1)  #¿Tiene el hogar servicio de: T.V. por cable?
  
)

# Realizar predicción
result_condicion <- predict(arbol_condicion4, vivienda_pred3, type = "class")
result_condicion  # Mostrar el resultado de la predicción
```





```{r}
####RANDOOOMM FOOOOREEESTTT
install.packages("randomForest")
```

```{r}
library(randomForest)

hogar <- read.csv('C:/Users/Andres/Desktop/Proyecto parte 2/vivienda.csv', sep=',')


hogar <- hogar[, c("POBREZA","P01H01",
"P01H02",
"P01H03",
"P01H04",
"P01H05",
"P01H06",
"P01H07",
"P01H08",
"P01H09",
"P01H10",
"P01H11",
"P01H12",
"P01H13",
"P01H14",
"P01H15",
"P01H16")]

hogar$POBREZA <- as.factor(hogar$POBREZA)

set.seed(100)
hogar <- hogar[sample(1:nrow(hogar)),]

index <-sample(1:nrow(hogar), 0.8*nrow(hogar))

train <- hogar[index,]
test <- hogar[-index,]

bosque <- randomForest(POBREZA ~

P01H01 +
P01H02 +
P01H03 +
P01H04 +
P01H05 +
P01H06 +
P01H07 +
P01H08 +
P01H09 +
P01H10 +
P01H11 +
P01H12 +
P01H13 +
P01H14 +
P01H15 +
P01H16,

                       data = train,
                       ntree = 200,
                       mtry = 10
                       )
prueba <- predict(bosque, test)

prueba

matriz <- table(test$POBREZA, prueba)

matriz

pre <- sum(diag(matriz)) / sum(matriz)
pre

plot(bosque)



```

```{r}
#CASO 1#

dato_nuevo <- data.frame(
P01H01 = 2, # ¿Usted se preocupó de que los alimentos se acabaran en su hogar?
P01H02 = 2, # ¿En su hogar se quedaron sin alimentos?
P01H03 = 2, # ¿En su hogar dejaron de tener una alimentación saludable y balanceada?
P01H04 = 1, # ¿Usted o algún adulto en su hogar tuvo una alimentación basada en poca variedad de alimentos?
P01H05 = 2, # ¿Usted o algún adulto en su hogar dejó de desayunar, almorzar o cenar?
P01H06 = 1, # ¿Usted o algún adulto en su hogar comió menos de lo que debía?
P01H07 = 2, # ¿Usted o algún adulto sintió hambre pero no comió?
P01H08 = 2, # ¿Usted o algún adulto en su hogar comió solo una vez al día o dejó de comer todo un día?
P01H09 = 1, # ¿En su hogar viven personas menores de 18 años? 
P01H10 = 2, # ¿Algún menor de 18 años en su hogar dejó de tener una alimentacion saludable y balanceada? 
P01H11 = 2, # ¿Algún menor de 18 años en su hogar tuvo una alimentacion basada en poca variedad de alimentos?
P01H12 = 2, # ¿Algún menor de 18 años en su hogar dejo de desayunar, almorzar o cenar?
P01H13 = 2, # ¿Algún menor de 18 años en su hogar comió menos de lo que debía?
P01H14 = 2, # ¿Tuvieron que disminuir la cantidad servida en las comidas a algún menor de 18 años en su hogar? 
P01H15 = 2, # ¿Algún menor de 18 años en su hogar sintió hambre pero no comió?
P01H16 = 2  # ¿Algún menor de 18 años en su hogar solo comió una vez al día o dejó de comer todo un día?
)

prediccion <- predict(bosque, dato_nuevo)
prediccion
```
```{r}
#CASO 2

dato_nuevo <- data.frame(
P01H01 = 1, # ¿Usted se preocupó de que los alimentos se acabaran en su hogar?
P01H02 = 1, # ¿En su hogar se quedaron sin alimentos?
P01H03 = 1, # ¿En su hogar dejaron de tener una alimentación saludable y balanceada?
P01H04 = 1, # ¿Usted o algún adulto en su hogar tuvo una alimentación basada en poca variedad de alimentos?
P01H05 = 2, # ¿Usted o algún adulto en su hogar dejó de desayunar, almorzar o cenar?
P01H06 = 1, # ¿Usted o algún adulto en su hogar comió menos de lo que debía?
P01H07 = 2, # ¿Usted o algún adulto sintió hambre pero no comió?
P01H08 = 2, # ¿Usted o algún adulto en su hogar comió solo una vez al día o dejó de comer todo un día?
P01H09 = 1, # ¿En su hogar viven personas menores de 18 años? 
P01H10 = 2, # ¿Algún menor de 18 años en su hogar dejó de tener una alimentacion saludable y balanceada? 
P01H11 = 2, # ¿Algún menor de 18 años en su hogar tuvo una alimentacion basada en poca variedad de alimentos?
P01H12 = 1, # ¿Algún menor de 18 años en su hogar dejo de desayunar, almorzar o cenar?
P01H13 = 1, # ¿Algún menor de 18 años en su hogar comió menos de lo que debía?
P01H14 = 1, # ¿Tuvieron que disminuir la cantidad servida en las comidas a algún menor de 18 años en su hogar? 
P01H15 = 2, # ¿Algún menor de 18 años en su hogar sintió hambre pero no comió?
P01H16 = 2  # ¿Algún menor de 18 años en su hogar solo comió una vez al día o dejó de comer todo un día?
)

prediccion <- predict(bosque, dato_nuevo)
prediccion
```

```{r}
library(randomForest)

hogar <- read.csv('C:/Users/Andres/Desktop/Proyecto parte 2/vivienda.csv', sep=',')


hogar <- hogar[, c("POBREZA",
"P01D01",
"P01D02",
"P01D03",
"P01D04",
"P01D05")]

hogar$DEPTO <- as.factor(hogar$POBREZA)

set.seed(100)
hogar <- hogar[sample(1:nrow(hogar)),]

index <-sample(1:nrow(hogar), 0.8*nrow(hogar))

train <- hogar[index,]
test <- hogar[-index,]

bosque <- randomForest(DEPTO ~

P01D01 +
P01D02 +
P01D03 +
P01D04 +
P01D05,

                       data = train,
                       ntree = 200,
                       mtry = 10
                       )
prueba <- predict(bosque, test)

prueba

matriz <- table(test$POBREZA, prueba)

matriz

pre <- sum(diag(matriz)) / sum(matriz)
pre

plot(bosque)


```
```{r}
#Prediccion 1

dato_nuevo <- data.frame(
P01D01 = 1,
P01D02 = 1,
P01D03 = 1,
P01D04 = 1,
P01D05 = 1
)

prediccion <- predict(bosque, dato_nuevo)
prediccion
```


```{r}
#Prediccion 2

dato_nuevo <- data.frame(
P01D01 = 1,
P01D02 = 2,
P01D03 = 2,
P01D04 = 5,
P01D05 = 2
)

prediccion <- predict(bosque, dato_nuevo)
prediccion
```

